### ISSUE TITLE
how to connect to go-ipfs

### ISSUE THREAD

**Issue by dborzov** [protocol/ipfs-webui#2]
OK, so this is probably a stupid question, but how do we bind this repo to the go-ipfs daemon? This repo does not seem to be a git submodule (or a subtree) of go-ipfs or anything.

We can install and compile go-ipfs, then initialize it and start up the daemon:
```sh
    ipfs init
   ipfs daemon
```
And then we look up `localhost:5001` and get the older version.

I am asking here rather than via IRC so that the answer will be searchable and public. 

What is the routine to checkout the newer versions?

**Comment by dborzov** [comment]
Ok, so we have got this suspicious dir [versions/](https://github.com/protocol/ipfs-webui/tree/master/versions), with hashes as titles. And the search tells as that one of the hashes is hardcoded here in go-ipfs: [/core/corehttp/webui.go](https://github.com/jbenet/go-ipfs/blob/94c64c577b5a1e8e123d9c033cba765261475c07/core/corehttp/webui.go).

So that is the answer, I suppose

**Comment by dborzov** [comment]
So it is actually hosted on ipfs, neat! How to set it up to develop and debug webui locally though?

**Comment by jbenet** [comment]
> So that is the answer, I suppose

Yeah, i think so. @mappum can answer best, he's the main dev on this.

> Running the gulp job does serve the dir statically, but there is no connection to ipfs daemon by default

Yeah, i think it assumes it's running locally and on ipfs? this will probably be best done with an ipns name . and probably adding without providing. it's probably worth adding a flag to `ipfs add` to not provide.

**Comment by travisperson** [comment]
I wrote a connect middleware for IPFS, could integrate this into the gulp file to proxy all /ipfs/ requests to the running daemon.

https://github.com/travisperson/ipfs-node-server-static

**Comment by jbenet** [comment]
@travisperson That SGTM.

**Comment by travisperson** [comment]
@dborzov did #8 fix this for you?

**Comment by dborzov** [comment]
:+1: @travisperson it did, awesome job, thanks a lot!

**Comment by travisperson** [comment]
@dborzov can you close this? (I can not)
